name: Run test suite and push Docker image
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests

  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t your-image-name:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: Rafik
          password: Rafik123+
      - name: Push Docker image
        run: docker push your-image-name:latest
