name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Déclencher le workflow uniquement pour les pushs sur la branche main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rafik1212
          password: rafik123+

      - name: Build and push MySQL image
        run: |
          docker-compose build mysql_db
          docker tag mysql rafik1212/mysql_db
          docker push rafik1212/mysql:latest

      - name: Build and push PHP image
        run: |
          docker-compose build php
          docker tag your_php_image rafik1212/your_php_image:latest
          docker push rafik1212/your_php_image:latest

      - name: Build and push phpMyAdmin image
        run: |
          docker-compose build phpmyadmin
          docker tag phpmyadmin rafik1212/phpmyadmin:latest
          docker push rafik1212/your_phpmyadmin_image:latest
