name: Build, Test, and Push

on:
  push:
    branches:
      - main  # Déclencher le workflow uniquement pour les pushs sur la branche main

jobs:
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rafik1212
          password: rafik123+

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # chemin du docker file
          push: true
          tags: rafik1212/sportify
